/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'martin' at '19/06/16 17:29' with Gradle 2.12
 *
 * @author martin, @date 19/06/16 17:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
